project:
  type: website
website:
  title: "mywebsite_6356"
  navbar:
    background: primary
    left:
      - text: "Home"
        href: index.qmd
    right:
      - icon: github
        href: https://github.com/sarahokra
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Example Section"
        contents:
          - about.qmd
  
format:
  html:
    theme: 
      light: flatly
      dark: darkly

